export const PRODUCT_TYPES={
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
    PAGE_NUMBER:"PAGE_NUMBER",
    FILTER_PRODUCTS:"FILTER-PRODUCTS",
    TOTALPAGES:"TOTALPAGES",
    CURRENT_PRODUCT:"CURRENT_PRODUCT",
    SEARCH_PRODUCT:"SEARCH_PRODUCT",
    SATRT_FETCHING_PRODUCTS:"START_FETCHING_PRODUCTS",
    SUCCESS_FETCHING_PRODUCTS:"SUCCESS_FETCHING_PRODUCTS",
    FAILURE_FETCHING_PRODUCTS:"FAILURE_FETCHING_PRODUCTS"
}