export const USER_TYPES={
    INSERT_USER:"INSERT_USER",
    ADD_PRODUCT:"ADD_PRODUCT",
    PRODUCT_COUNT:"PRODUCT_COUNT",
    DELETE_PRODUCT:"DELETE_PRODUCT",
    SET_POPUP:"SET_POPU",
    IS_LOADING:"IS_LOADING",
    USER_LOG_OUT:"USER_LOG_OUT",
    THEME:"THEME"
}
